/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/paywall`; params?: Router.UnknownInputParams; } | { pathname: `/results`; params?: Router.UnknownInputParams; } | { pathname: `/scanner`; params?: Router.UnknownInputParams; } | { pathname: `/results-preview`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/coach` | `/coach`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/program` | `/program`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scan` | `/scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tracker` | `/tracker`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/body-scan`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/face-intro`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/face-scan`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/gender`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/goals`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/referral`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/paywall`; params?: Router.UnknownOutputParams; } | { pathname: `/results`; params?: Router.UnknownOutputParams; } | { pathname: `/scanner`; params?: Router.UnknownOutputParams; } | { pathname: `/results-preview`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/coach` | `/coach`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/program` | `/program`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/scan` | `/scan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tracker` | `/tracker`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/body-scan`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/face-intro`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/face-scan`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/gender`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/goals`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/referral`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/dashboard${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/paywall${`?${string}` | `#${string}` | ''}` | `/results${`?${string}` | `#${string}` | ''}` | `/scanner${`?${string}` | `#${string}` | ''}` | `/results-preview${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/coach${`?${string}` | `#${string}` | ''}` | `/coach${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/program${`?${string}` | `#${string}` | ''}` | `/program${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/scan${`?${string}` | `#${string}` | ''}` | `/scan${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tracker${`?${string}` | `#${string}` | ''}` | `/tracker${`?${string}` | `#${string}` | ''}` | `/onboarding/body-scan${`?${string}` | `#${string}` | ''}` | `/onboarding/face-intro${`?${string}` | `#${string}` | ''}` | `/onboarding/face-scan${`?${string}` | `#${string}` | ''}` | `/onboarding/gender${`?${string}` | `#${string}` | ''}` | `/onboarding/goals${`?${string}` | `#${string}` | ''}` | `/onboarding/notifications${`?${string}` | `#${string}` | ''}` | `/onboarding/referral${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/paywall`; params?: Router.UnknownInputParams; } | { pathname: `/results`; params?: Router.UnknownInputParams; } | { pathname: `/scanner`; params?: Router.UnknownInputParams; } | { pathname: `/results-preview`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/coach` | `/coach`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/program` | `/program`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/scan` | `/scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tracker` | `/tracker`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/body-scan`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/face-intro`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/face-scan`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/gender`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/goals`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/referral`; params?: Router.UnknownInputParams; };
    }
  }
}
